# Generated by Django 2.0.4 on 2018-04-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_game_name', models.CharField(max_length=100)),
                ('comment_num', models.IntegerField()),
                ('favorable_rate', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('discount_price', models.FloatField()),
            ],
        ),
    ]
