# Generated by Django 2.0.4 on 2018-04-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Origin',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='source',
            new_name='origin',
        ),
    ]
