# Generated by Django 2.0.4 on 2018-04-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_library', '0002_auto_20180424_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
