# Generated by Django 2.0.4 on 2018-04-25 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_library', '0004_auto_20180424_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
    ]
