# Generated by Django 2.0.4 on 2018-04-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_library', '0007_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_library.Origin'),
        ),
    ]
