# Generated by Django 2.0.4 on 2018-04-25 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_library', '0008_post_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
