# Generated by Django 2.0.4 on 2018-04-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_library', '0010_auto_20180425_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified_time',
        ),
    ]
