# Generated by Django 2.0.4 on 2018-04-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_library', '0011_remove_post_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
