# Generated by Django 2.0.4 on 2018-04-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
