# Generated by Django 2.0.4 on 2018-05-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_auto_20180428_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_job_execution_id', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('running_status', models.IntegerField(default=0)),
                ('running_on', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=100)),
                ('tags', models.TextField()),
                ('spider_arguments', models.TextField()),
                ('priority', models.IntegerField()),
                ('desc', models.TextField()),
                ('cron_minutes', models.CharField(default='0', max_length=100)),
                ('cron_hour', models.CharField(default='*', max_length=100)),
                ('cron_day_of_month', models.CharField(default='*', max_length=100)),
                ('cron_day_of_week', models.CharField(default='*', max_length=100)),
                ('cron_month', models.CharField(default='*', max_length=100)),
                ('enabled', models.IntegerField(default=0)),
                ('run_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpiderInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Project')),
            ],
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Project'),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='job_instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.JobInstance'),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Project'),
        ),
    ]
